# Generated by Django 4.1.5 on 2023-01-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('age', models.IntegerField(null=True)),
                ('client_id', models.CharField(max_length=100, null=True)),
                ('agency_id', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('status_reason', models.CharField(max_length=100, null=True)),
                ('industry', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('active_for_dealer_track', models.BooleanField(null=True)),
                ('active_for_route_one', models.BooleanField(null=True)),
                ('active_for_experian', models.BooleanField(null=True)),
                ('active_for_trans_union', models.BooleanField(null=True)),
                ('active_for_equifax', models.BooleanField(null=True)),
                ('creation_date', models.DateField(null=True)),
                ('creation_time', models.TimeField(null=True)),
                ('business_name', models.CharField(max_length=100, null=True)),
                ('address_line_1', models.CharField(max_length=255, null=True)),
                ('address_line_2', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('zip', models.CharField(max_length=10, null=True)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('fax_number', models.CharField(max_length=20, null=True)),
                ('preferred_payment_method', models.CharField(max_length=100, null=True)),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('routing_number', models.CharField(max_length=100, null=True)),
                ('bank_account_number', models.CharField(max_length=100, null=True)),
                ('cosigner_fico_qualification_limit', models.IntegerField(null=True)),
                ('assigned_sales_rep', models.CharField(max_length=100, null=True)),
                ('required_reference_verifications', models.CharField(max_length=100, null=True)),
                ('contact_1_name', models.CharField(max_length=100, null=True)),
                ('contact_1_job_title', models.CharField(max_length=100, null=True)),
                ('contact_1_phone_number', models.CharField(max_length=20, null=True)),
                ('contact_1_email_address', models.EmailField(max_length=254, null=True)),
                ('contact_2_name', models.CharField(max_length=100, null=True)),
                ('contact_2_job_title', models.CharField(max_length=100, null=True)),
                ('contact_2_phone_number', models.CharField(max_length=20, null=True)),
                ('contact_2_email_address', models.EmailField(max_length=254, null=True)),
                ('contact_3_name', models.CharField(max_length=100, null=True)),
                ('contact_3_job_title', models.CharField(max_length=100, null=True)),
                ('contact_3_phone_number', models.CharField(max_length=20, null=True)),
                ('contact_3_email_address', models.EmailField(max_length=254, null=True)),
                ('support_contact_name', models.CharField(max_length=100, null=True)),
                ('support_contact_job_title', models.CharField(max_length=100, null=True)),
                ('support_contact_phone_number', models.CharField(max_length=20, null=True)),
                ('support_contact_email_address', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('job_description', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('supervisor', models.CharField(blank=True, max_length=255)),
                ('employment_type', models.CharField(blank=True, max_length=255)),
                ('employment_status', models.CharField(blank=True, max_length=255)),
                ('company_phone', models.CharField(blank=True, max_length=255)),
                ('extension', models.CharField(blank=True, max_length=255)),
                ('seat_location', models.CharField(blank=True, max_length=255)),
                ('company_email_address', models.CharField(blank=True, max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
