# Generated by Django 5.0.6 on 2024-06-04 18:55

import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_retrieving', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=store.models.brand_upload_to)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('checked_out', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('paid_transaction_id', models.CharField(blank=True, max_length=255)),
                ('billing_address_line1', models.CharField(blank=True, max_length=255)),
                ('billing_address_line2', models.CharField(blank=True, max_length=255)),
                ('billing_city', models.CharField(blank=True, max_length=255)),
                ('billing_state', models.CharField(blank=True, max_length=255)),
                ('billing_zipcode', models.CharField(blank=True, max_length=255)),
                ('billing_country', models.CharField(blank=True, max_length=255)),
                ('shipping_address_line1', models.CharField(blank=True, max_length=255)),
                ('shipping_address_line2', models.CharField(blank=True, max_length=255)),
                ('shipping_city', models.CharField(blank=True, max_length=255)),
                ('shipping_state', models.CharField(blank=True, max_length=255)),
                ('shipping_zipcode', models.CharField(blank=True, max_length=255)),
                ('shipping_country', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=store.models.category_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(default=store.models.default_uuid, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('your_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('source_upload', models.TextField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=store.models.product_upload_to)),
                ('display_priority', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('wholesale_price_item_json', models.TextField(null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mint', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_uri', models.URLField(blank=True, null=True)),
                ('metadata_uri', models.URLField(blank=True, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram', models.CharField(blank=True, max_length=100, null=True)),
                ('bonding_curve', models.CharField(blank=True, max_length=100, null=True)),
                ('associated_bonding_curve', models.CharField(blank=True, max_length=100, null=True)),
                ('creator', models.CharField(blank=True, max_length=100, null=True)),
                ('created_timestamp', models.DateTimeField(blank=True, null=True)),
                ('raydium_pool', models.CharField(blank=True, max_length=100, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('virtual_sol_reserves', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('virtual_token_reserves', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('total_supply', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('show_name', models.BooleanField(default=False)),
                ('last_trade_timestamp', models.DateTimeField(blank=True, null=True)),
                ('king_of_the_hill_timestamp', models.DateTimeField(blank=True, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('reply_count', models.IntegerField(blank=True, null=True)),
                ('last_reply', models.CharField(blank=True, max_length=100, null=True)),
                ('nsfw', models.BooleanField(default=False)),
                ('market_id', models.IntegerField(blank=True, null=True)),
                ('inverted', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('usd_market_cap', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='seat_location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='user',
            name='billing_address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_zipcode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hrn_company_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_zipcode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
