# Generated by Django 5.0.6 on 2024-06-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_apidata_brand_cart_cartproduct_category_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='mint',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
