# Generated by Django 5.0.6 on 2024-06-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_token_mint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='twitter',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
